### ISSUE TITLE
Textures not showing in 3D view.

### ISSUE THREAD

**Issue by Helioform** [TTimo/GtkRadiant#512] opened 2017-06-13 23:12 UTC
Hi, 

there is no texture being rendered in the 3D view of the editor. There are only colored lines. 
Here is the screenshot: https://www.dropbox.com/s/8ukofv18or4dqjd/qtkrad.png?dl=1
I'm on Windows 10, but the issue was present also on Win7 when I had that OS. My video card is an Intel HD Graphics. -EDIT, forgot to say that the issue is on RTCW maps, but I haven't tried other games.
Thanks.

**Comment by ensiform** [comment] 2017-06-14 00:55
Looks like you have the 3d view set to wireframe mode.

I'm not sure how to fix that off hand.

**Comment by 0bsidian** [comment] 2017-06-19 17:00
I believe this is a known issue with Intel graphics, there is an easy fix in preferences. See below:

https://www.katsbits.com/smforum/index.php?topic=328.0

**Comment by TTimo** [comment] 2017-06-19 18:49
Well shoot - I got rid of that hack recently, assuming that drivers had either evolved far enough to not be shitty anymore, or this only happened on old hardware that nobody cared about ..

**Comment by Helioform** [comment] 2017-06-19 18:59
The info provided on that link helped me fix it. Thanks.
And yes it is shitty/old hardware that is this Intel video card. But at least I can play RTCW well on it...and this card is only temporary.

**Comment by TTimo** [comment] 2017-06-19 19:01
But how did you fix it - still had to apply the workaround? If it's still there in the older build you are running, it'll be gone on the next one we do.

**Comment by Helioform** [comment] 2017-06-19 19:02
I had to use the second fix because it was persistant. Hiding everything did the trick.

**Comment by KatsBits** [comment] 2017-06-19 23:18
@TTimo if you can keep that "ATI... " fix in as a 'Legacy Option' of some kind that would be great. Still a lot of users on Intel, and they have poor openGL support which seems to be the cause of the problem mentioned by the OP.

**Comment by ensiform** [comment] 2017-06-19 23:23
Why nobody hounds Intel to fix their shit on all platforms for GL is beyond me.  There's more than enough GL programs out there

**Comment by KatsBits** [comment] 2017-06-20 01:38
They *were* hounded about it.. but even back in the glory days of PC Master Race, ID and EPIC couldn't get them to properly address the issue.

**Comment by 0bsidian** [comment] 2017-06-20 11:23
If adding the option back in, perhaps it might be logical to take the opportunity to rename the option, "AMD/Intel GPU display bug fix".

**Comment by TTimo** [comment] 2017-08-05 20:51
Brought back the workaround. Will be in next build (soon).

**Closed by TTimo** 2017-08-05 20:51 UTC
